In [1]:
#%pip install iisignature
import torch
import signatory
import iisignature
import time
import numpy

ModuleNotFoundError: No module named 'iisignature'

In [2]:

import torch
import signatory
import iisignature
import time
import numpy as np

runs, max_length = 10, 4
channels, sig_depth = 3, 4
times_iisig = np.zeros(max_length)
times_signatory = np.zeros(max_length)

for j in range(runs):
    for i in range(max_length):
        path = torch.rand(10**(i+1), channels)

        start = time.time()
        sig = iisignature.sig(path, sig_depth)
        end = time.time()
        times_iisig[i] += (end - start)    
        del(sig)

        path = path.unsqueeze(0)
        start = time.time()
        sig = signatory.signature(path, sig_depth)
        end = time.time()
        times_signatory[i] += (end - start)
        del(path, sig)

print('Times iisignsture: \n', times_iisig / runs)
print('Times signatory: \n ', times_signatory / runs)
print('Speed up: \n', times_signatory / times_iisig)
print('Average speed up:', (times_signatory / times_iisig).mean())


Times iisignsture: 
 [0.00011394 0.00012352 0.00094166 0.00902739]
Times signatory: 
  [0.00049684 0.00071456 0.00335073 0.01670105]
Speed up: 
 [4.36053568 5.78479058 3.55833502 1.85004331]
Average speed up: 3.8884261481309217
